"use client";

import { ArrowDown, ArrowUp, ArrowUpDown, CopyPlus, Plus, Trash2 } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Checkbox } from "@/components/ui/checkbox";
import { Input } from "@/components/ui/input";
import { Table, TBody, TD, TH, THead } from "@/components/ui/table";

export type SortDirection = "asc" | "desc";

export function DataBrowserTable({
  columns,
  rows,
  rowKeyMap,
  selectedRowKeys,
  onToggleRowSelected,
  onToggleAllRowsSelected,
  allRowsSelected,
  columnWidths,
  onResizeColumn,
  newRow,
  isAutoGeneratedColumn,
  onChangeNewRow,
  onInsertRow,
  editingCell,
  editValue,
  onChangeEditValue,
  onStartEdit,
  onCommitEdit,
  onCancelEdit,
  onDuplicateRow,
  onDeleteRow,
  sortBy,
  sortDirection,
  onSort,
  loading,
}: {
  columns: string[];
  rows: Record<string, unknown>[];
  rowKeyMap: string[];
  selectedRowKeys: Set<string>;
  onToggleRowSelected: (rowKey: string) => void;
  onToggleAllRowsSelected: () => void;
  allRowsSelected: boolean;
  columnWidths: Record<string, number>;
  onResizeColumn: (column: string, startX: number) => void;
  newRow: Record<string, string>;
  isAutoGeneratedColumn: (column: string) => boolean;
  onChangeNewRow: (column: string, value: string) => void;
  onInsertRow: () => void;
  editingCell: { rowKey: string; column: string } | null;
  editValue: string;
  onChangeEditValue: (value: string) => void;
  onStartEdit: (row: Record<string, unknown>, rowKey: string, column: string, value: string) => void;
  onCommitEdit: () => void;
  onCancelEdit: () => void;
  onDuplicateRow: (row: Record<string, unknown>) => void;
  onDeleteRow: (row: Record<string, unknown>) => void;
  sortBy?: string;
  sortDirection?: SortDirection;
  onSort: (column: string) => void;
  loading?: boolean;
}) {
  return (
    <div className="flex-1 overflow-auto dark:border-neutral-800">
      <Table className="min-w-max">
        <THead>
          <tr>
            <TH className="sticky top-0 z-10 w-10 bg-neutral-100 px-2 backdrop-blur dark:bg-neutral-900">
              <Checkbox checked={allRowsSelected} onChange={onToggleAllRowsSelected} />
            </TH>
            <TH className="sticky top-0 z-10 w-16 bg-neutral-100 text-right text-[11px] font-medium text-neutral-500 backdrop-blur dark:bg-neutral-900 dark:text-neutral-400">
              #
            </TH>
            {columns.map((column) => (
              <TH
                key={column}
                className="group sticky top-0 z-10 bg-neutral-100 pr-5 text-[11px] font-medium text-neutral-500 backdrop-blur dark:bg-neutral-900 dark:text-neutral-400"
                style={{ width: columnWidths[column] ?? 180, minWidth: 110, maxWidth: columnWidths[column] ?? 180 }}
              >
                <button
                  type="button"
                  onClick={() => onSort(column)}
                  className="inline-flex items-center gap-1 hover:text-neutral-900 dark:hover:text-neutral-100"
                >
                  <span className="truncate">{column}</span>
                  {sortBy !== column ? (
                    <ArrowUpDown className="h-3 w-3" />
                  ) : sortDirection === "asc" ? (
                    <ArrowUp className="h-3 w-3" />
                  ) : (
                    <ArrowDown className="h-3 w-3" />
                  )}
                </button>
                <button
                  type="button"
                  className="absolute top-0 right-0 h-full w-2 cursor-col-resize border-l border-neutral-300/60 bg-neutral-200/20 opacity-30 hover:opacity-100 dark:border-neutral-700"
                  onMouseDown={(event) => {
                    event.preventDefault();
                    onResizeColumn(column, event.clientX);
                  }}
                  title="Resize column"
                />
              </TH>
            ))}
            <TH className="sticky top-0 z-10 w-[100px] bg-neutral-100 text-center text-[11px] font-medium text-neutral-500 backdrop-blur dark:bg-neutral-900 dark:text-neutral-400">
              Actions
            </TH>
          </tr>
        </THead>
        <TBody>
          <tr className="bg-neutral-100/60 dark:bg-neutral-900/80">
            <TD className="px-2 align-middle" />
            <TD className="align-middle text-right font-mono text-xs text-neutral-500 dark:text-neutral-400">+</TD>
            {columns.map((column) => {
              const autoGenerated = isAutoGeneratedColumn(column);
              return (
                <TD key={`new-${column}`} className="p-0 align-middle" style={{ width: columnWidths[column] ?? 180, minWidth: 110 }}>
                  <Input
                    value={newRow[column] ?? ""}
                    onChange={(event) => onChangeNewRow(column, event.target.value)}
                    disabled={autoGenerated}
                    placeholder={autoGenerated ? "auto" : ""}
                    className="h-full min-h-[36px] w-full rounded-none border-0 bg-transparent px-2 font-mono text-xs focus-visible:ring-1 focus-visible:ring-inset focus-visible:ring-neutral-300 dark:focus-visible:ring-neutral-700"
                  />
                </TD>
              );
            })}
            <TD className="text-center">
              <Button size="sm" className="h-8 w-8 bg-neutral-900 p-0 text-white hover:bg-black dark:bg-white dark:text-black dark:hover:bg-neutral-200" onClick={onInsertRow} title="Insert row">
                <Plus className="h-4 w-4" />
              </Button>
            </TD>
          </tr>

          {loading ? (
            <tr>
              <TD colSpan={columns.length + 3} className="h-24 text-center text-xs text-neutral-500 dark:text-neutral-400">
                Loading rows...
              </TD>
            </tr>
          ) : null}

          {rows.map((row, rowIdx) => {
            const rowKey = rowKeyMap[rowIdx] ?? String(rowIdx);
            return (
              <tr
                key={rowKey}
                className={
                  rowIdx % 2 === 0
                    ? "bg-white hover:bg-neutral-100/90 dark:bg-neutral-950 dark:hover:bg-neutral-800/80"
                    : "bg-neutral-50/60 hover:bg-neutral-100 dark:bg-neutral-900/40 dark:hover:bg-neutral-800"
                }
              >
                <TD className="px-2 align-middle">
                  <Checkbox checked={selectedRowKeys.has(rowKey)} onChange={() => onToggleRowSelected(rowKey)} />
                </TD>
                <TD className="align-middle text-right font-mono text-xs text-neutral-500 dark:text-neutral-400">{rowIdx + 1}</TD>
                {columns.map((column) => {
                  const value = row[column];
                  const isEditing = editingCell?.rowKey === rowKey && editingCell.column === column;
                  return (
                    <TD key={`${rowKey}-${column}`} className="p-0 align-middle" style={{ width: columnWidths[column] ?? 180, minWidth: 110 }}>
                      {isEditing ? (
                        <Input
                          autoFocus
                          value={editValue}
                          onChange={(event) => onChangeEditValue(event.target.value)}
                          onBlur={onCommitEdit}
                          onKeyDown={(event) => {
                            if (event.key === "Enter") {
                              event.preventDefault();
                              onCommitEdit();
                            }
                            if (event.key === "Escape") {
                              onCancelEdit();
                            }
                          }}
                          className="h-full min-h-[36px] w-full rounded-none border-0 bg-transparent px-2 font-mono text-xs focus-visible:ring-1 focus-visible:ring-inset focus-visible:ring-neutral-300 dark:focus-visible:ring-neutral-700"
                        />
                      ) : (
                        <button
                          type="button"
                          className="flex h-full min-h-[36px] w-full items-center truncate px-2 text-left font-mono text-xs text-neutral-700 hover:bg-neutral-200/70 dark:text-neutral-200 dark:hover:bg-neutral-700/70"
                          title={String(value ?? "")}
                          onClick={() => onStartEdit(row, rowKey, column, String(value ?? ""))}
                          onKeyDown={(event) => {
                            if (event.key === "Enter") {
                              event.preventDefault();
                              onStartEdit(row, rowKey, column, String(value ?? ""));
                            }
                          }}
                        >
                          {String(value ?? "")}
                        </button>
                      )}
                    </TD>
                  );
                })}
                <TD className="align-middle">
                  <div className="flex items-center justify-center gap-1">
                    <Button
                      size="sm"
                      variant="outline"
                      className="h-7 w-7 border-neutral-300 bg-neutral-100 p-0 hover:bg-neutral-200 dark:border-neutral-700 dark:bg-neutral-900 dark:hover:bg-neutral-800"
                      onClick={() => onDuplicateRow(row)}
                      title="Duplicate row"
                    >
                      <CopyPlus className="h-3.5 w-3.5" />
                    </Button>
                    <Button
                      size="sm"
                      variant="destructive"
                      className="h-7 w-7 p-0"
                      onClick={() => onDeleteRow(row)}
                      title="Delete row"
                    >
                      <Trash2 className="h-3.5 w-3.5" />
                    </Button>
                  </div>
                </TD>
              </tr>
            );
          })}
        </TBody>
      </Table>
    </div>
  );
}
